name: "Comelit Virtual Module"
description: "Integrazione alla domotica Comelit"
version: "1.0.0"
slug: "comelit-vmod"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  comelit-ip: "192.168.1.51"
  comelit-port: 10011
  comelit-password: ""
  modules:
    - address: 1
      name: "Virtual I8"
      initial-state: 0
schema:
  comelit-ip: "str"
  comelit-port: "int(1,65535)"
  comelit-password: "password"
  modules:
    - address: "int(1,255)"
      name: "str"
      initial-state: "int(0,255)"
